---
title: "High-dimensional phase space measurements"
date: 2023-05-28
author: Austin Hoover
categories: [accelerators, high-dimensional data, visualization]
bibliography: references.bib
csl: american-physics-society.csl
---


This post is a brief description of some recent work at my ORNL postdoc. Some of this work was recently published in Physical Review Accelerators and Beams (link).


## 1. The challenge of predicting intense beam dynamics

Modern linear accelerators (linacs) generate powerful pulsed hadron beams for various applications. Significantly increasing the beam power is challenging due to *beam loss*, which occurs when particles hit the walls of the accelerator during their journey. The total lost beam power must not exceed 1 watt (W) per meter along the beamline to avoid dangerous radiation levels. For a typical 1 MW beam, this corresponds to a fractional loss of $10^{-6}$ --- one out of every million particles.

Simulations cannot currently predict the number and location of lost particles. The beam dynamics in the accelerator are complex, but the majority opinion is that the physics is modeled correctly. The situation is perhaps unsurprising for other reasons:

1. Accelerators are composed of thousands of components distributed over hundreds of meters. Uncertainties in the position, alignment, amplitude, etc. of each component lead to errors in the applied electromagnetic field at each position.

2. The initial distribution of particles in position-momentum space (phase space) is usually unknown.

These issues make it difficult to predict even the low-order moments of the beam distribution, let alone low levels of beam loss.

These difficulties were highlighted by the LEDA (Low Energy Test Accelerator) experiment at Los Alamos National Laboratory, where one-dimensional (1D) density profiles of a low-energy proton beam were measured after the beam was transported through a short series of focusing magnets. Following the experiment, particle-in-cell (PIC) simulations were performed with various initial phase space distributions and compared to the measurements. The following figure is one example, with markers representing measurements and lines representing simulations.

[image]

Each measured profile has a dense core surrounded by a low-density "halo" with a large spatial extent; none of the simulations correctly predicted the halo density. 



## 2. High-dimensional phase space measurements at the SNS Beam Test Facility (BTF)

The Beam Test Facility (BTF), a replica of the front-end of the SNS linac, has been constructed to repeat the LEDA experiment with improved diagnostic capabilities. The BTF has pioneered high-dimensional phase space measurements to eliminate the uncertainty in the initial beam distribution. Our hope is that these measurements, when combined with a detailed model of the accelerator and a well-tested simulation code, will allow us to predict the beam evolution at the halo level in the BTF. This would be a first step toward beam loss prediction in the much longer SNS linac.

[image]

The H- beam in the BTF begins at the ion source and is guided through the low-energy beam tranport (LEBT) using electrostatic focusing. At this point, the beam is a slow-moving, continous stream of ions. The beam then passes through the radiofrequency quadrupole (RFQ), which provides both focusing and acceleration up to 2.5 MeV. After the RFQ, the beam is a train of small bunches. Each bunch drifts through the medium-energy beam transport (MEBT) before passing through a series of permanent quadrupole magnets at the end of the beamline. 

Here I focus on the measurement apparatus just after the RFQ. The measurement works by measuring the charge within a small region of phase space $\mathbf{x} \pm \Delta$, where $\mathbf{x} = [x, p_x, y, p_y, z, p_z]^T$ is the phase space coordinate vector (the $z$ axis is paralell to the beam). The density $f(\mathbf{x})$ is interpolated by scanning $\mathbf{x}$ through the phase space.

The phase space coordinates are isolated using slits. First, a horizontal-vertical pair of slits is used to select $x$ and $y$. Next, a second pair of slits is used to select $p_x$ and $p_y$ (based on the positions relative to the first slits). The longitudinal coordinates ($z$, $p_z$) are trickier. The momentum $p_z$ is selected using a dipole magnet, which bends on-energy particles 90 degrees. Since faster particles bend less, a vertical slit  after the dipole isolates $p_z$. The last to go is the $z$ coordinate. The beam passes through a wire, which generates an electron beam with the same time structure. Since the electrons are much less massive, they can be streaked in the transverse plane using an oscillating electric field. The streaking essentially rotates the beam in the $x$-$z$ plane, so the image of the beam on a screen gives the $z$ distribution. 

[image]

We perform the measurement by scanning the slits in a nested loop, recording the image of the beam on the screen at each setting. Each pixel in the image is the intensity at a point in phase space. By interpolating the data, we obtain an estimate of the 6D phase space distribution $f(\mathbf{x})$.

After the phase space distribution $f(\mathbf{x})$ is inferred, we generate a set of phase space coordinates $\{\mathbf{x}_1, \dots \mathbf{x}_n\}$ by sampling from the distribution. These coordinates are propagated through a computational model of the accelerator and compared with measurements at the end of the beamline. The BTF is equipped to measure $\{f(x, p_x), f(y, p_y)\}$ with high dynamic range, i.e., we can measure the low-density halo in 2D phase space. Our hope is that the predicted 2D phase space distribution agrees with the measurements in the halo region --- where the density is four to six orders of magnitude below the peak density in the core. The entire workflow is illustrated below.



## 3. High-dimensional data visualization

Most of my time thus far has been spent analyzing the initial phase space distribution using high-dimensional measurements. The rest of this post will describe our data processing and visualization in a bit more detail.

At the moment, our 6D measurements are quite slow and fail to capture very fine details in the distribution. Dropping one dimension ($z$) significantly increases the resolution and dynamic range while capturing most interesting correlations. Thus, we used 5D measurements in these studies.

The actuators and diagnostics in the BTF are controlled using Python scripts. After receiving the scan limits, number of steps, and other information, the script continously moves the slits, recording the image on each beam pulse (5 per second). The following image shows the measured image brightness and beam current (out of the RFQ) during the 18-hour scan. 

[image]

This scan generated ???,??? images (??? GB)! These images were cropped and downscaled to decrease the size of the data set to around 36 GB. Next, the pixel intensities were interpolated onto a regular grid in 5D phase space, forming a 5D image. This data processing was actually quite fast, taking only a few minutes. Here is an example output from one of the analysis notebooks.

The next task is to visualize the data. 

Planar slicing

Non-planar slicing