---
title: "Austin Hoover"
---

[I](me.qmd) am a physicist in the Accelerator Physics Group at [Oak Ridge National Laboratory](https://www.ornl.gov). I'm interested in techniques to model, measure, and control intense charged particle beams in particle accelerators. I currently focus on (i) theory and modeling of collective effects, such as halo formation and instabilities, (ii) phase space shaping and manipulation, and (iii) inverse problems such as phase space tomography. [Here](./research/index.qmd) is a more detailed overview of my research. I sometimes write about my work on my [blog](https://austin-hoover.github.io/blog/).


## Selected Papers

[N-dimensional maximum-entropy tomography via particle sampling](https://journals.aps.org/prab/pdf/10.1103/zl2h-3v32). 
A. Hoover. 
*Phys. Rev. Accel. Beams 28, L084601* (2025).

[Four-dimensional phase space tomography from one-dimensional measurements of a hadron beam](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.27.122802). 
A. Hoover.
*Phys. Rev. Accel. Beams 27, 122802* (2024).

[High-dimensional maximum-entropy phase space tomography using normalizing flows](https://journals.aps.org/prresearch/pdf/10.1103/PhysRevResearch.6.033163).
A. Hoover, and J.C. Wong.
*Phys. Rev. Research 6.3, 033163* (2024).

[Analysis of a hadron beam in five-dimensional phase space](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.26.064202).
A. Hoover, K. Ruisard, A. Aleksandrov, A. Zhukov, and S. Cousineau.
*Phys. Rev. Accel. Beams 26.6, 064202* (2023).

[Computation of the matched envelope of the Danilov distribution](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.24.044201).
A. Hoover, N. Evans, and J. Holmes.
*Phys. Rev. Accel. Beams 24.4, 044201 (2021).


## Selected Talks


[High-dimensional maximum-entropy phase space tomography](./talks/files/2025-08-12_napac_ment.pdf).
*North American Particle Accelerator Conference*. Sacramento, USA. (2025-08-12)

[Bunch rotation experiments and benchmarking at SNS](https://indico.desy.de/event/45968/contributions/186224/).
*International Muon Collider Collaboration Meeting*. Hamburg, Germany. (2025-05-13)

[The impact of high-dimensional phase space correlations on the beam dynamics in a linear accelerator](https://accelconf.web.cern.ch/hb2023/talks/tuc1c2_talk.pdf).
*ICFA Workshop on High-Intensity and High-Brightness Hadron Beams*. Geneva, Switzerland. (2023-10-10)

[Self-consistent, angular-momentum-dominated hadron beams for space charge mitigation](https://conference.sns.gov/event/335/contributions/528/attachments/892/8194/2022-10-26_Hoover_space_charge_workshop.pdf). *ICFA Mini-Workshop on Space Charge*. Knoxville, USA. (2022-10-06)


## Links

[Blog](https://austin-hoover.github.io/blog/) \
[ORNL staff profile](https://www.ornl.gov/staff-profile/austin-hoover) \
[ORCID](https://orcid.org/0000-0001-5313-6962) \
[Google Scholar](https://scholar.google.com/citations?user=ReHwHZcAAAAJ&hl=en&oi=ao) \
[GitHub](https://github.com/austin-hoover) \
[LinkedIn](https://www.linkedin.com/in/austinhoover0/) \
