---
title: "Current topics"
---

Things I'm working on, thinking about, or hoping to think about at some point:

* General
    * Intense beam dynamics in circular accelerators (rings)
    * Intense beam dynamics in linear accelerators (linacs)
    * Inverse problems
* Accelerator physics
    * Halo formation and beam loss prediction in high-power linacs
    * Phase space painting of equilibrium distributions
    * Phase space painting in strongly coupled lattices
    * Phase space painting in nonlinear rings
    * Proton bunch compression
    * Simulation benchmarking
* Theory/modeling
    * Single-particle dynamics in strongly coupled systems
    * Multi-particle dynamics in strongly coupled systems
    * Vlasov-Poisson equilibrium distributions 
    * Space-charge-driven resonances and instabilities
* Phase space measurements and inference
    * High-dimensional phase space measurements (direct)
    * High-dimensional phase space tomography
    * High-dynamic-range phase space tomography
    * Uncertainty quantification in phase space tomography
    * Phase space tomography with self-consistent space charge forces
    * Maximum-entropy techniques for inverse problems
    * Bayesian inference for phase space measurements
* Optimization, machine learning, etc.
    * Generative models for accelerator applications
    * Surrogate modeling of intense beam dynamics
    * Online optimization of phase space painting waveforms
    * Differentiable simulations
    * Adjoint methods for optimization of beam parameters 

