---
title: "News"
format:
  html:
    css: style.css
---

<dl class="news-dl">

<dt>JAN 2026</dt>
<dd>Paper: [Demonstration of a novel phase space painting method in a coupled lattice to mitigate space charge in high-intensity hadron beams](https://arxiv.org/pdf/2601.13517) was accepted for publication in PRL. Coauthors: Nick Evans, Vasiliy Morozov, Timofey Gorlov. </dd>

<dt>DEC 2025</dt>
<dd>Joined [USMCC](https://www.muoncollider.us).</dd>

<dt>AUG 2025</dt>
<dd>Talk: [High-dimensional maximum-entropy phase space tomography](https://drive.google.com/file/d/1D6URvUgqFryMU3Eq70PdiAzkym7n7SkZ/view?usp=share_link) at NAPAC25 in Sacramento.</dd>

<dt>AUG 2025</dt>
<dd>Talk: [Proton Driver for the Demonstrator and Muon Collider](https://indico.uchicago.edu/event/479/contributions/1999/attachments/782/1296/main.pdf) at USMCC Annual Meeting at the University of Chicago.</dd>

<dt>MAY 2025</dt>
<dd>Paper: [N-dimensional maximum-entropy tomography via particle sampling](https://arxiv.org/pdf/2409.17915) accepted for publication in PRAB (Letter, Editors' Suggestion).</dd>

<dt>MAY 2025</dt>
<dd>Talk: [Bunch rotation experiments and benchmarking at SNS](https://indico.desy.de/event/45968/contributions/186224/attachments/97097/133487/main.pptx) at the IMCC Annual Meeting in Hamburg. (Presented remotely.)</dd>

<dt>JUL 2024</dt>
<dd>Paper: [High-dimensional maximum-entropy phase space tomography using normalizing flows](https://arxiv.org/pdf/2406.00236) accepted for publication in PRResearch. Coauthor: Jonathan Chun Wong.</dd>

<dt>MAY 2024</dt>
<dd>Poster: [MENT-Flow: maximum-entropy tomography using normalizing flows](https://www.jacow.org/ipac2024/pdf/WEPG65.pdf) at IPAC24 in Nashville.</dd>

<dt>APR 2024</dt>
<dd>Started Associate Scientist position at Oak Ridge National Laboratory.</dd>

<dt>OCT 2023</dt>
<dd>Talk: [The impact of high-dimensional phase space correlations on the beam dynamics in a linear accelerator](https://accelconf.web.cern.ch/hb2023/talks/tuc1c2_talk.pdf) at HB23 in Geneva.</dd>

<dt>MAY 2023</dt>
<dd>Poster: [Detailed characterization of a five-dimensional phase space distribution](https://accelconf.web.cern.ch/ipac2023/pdf/WEPA028.pdf) at IPAC23 in Venice.</dd>

<dt>MAY 2023</dt>
<dd>Paper: [Analysis of a hadron beam in five-dimensional phase space](https://arxiv.org/pdf/2301.04178) was accepted for publication in PRAB. Coauthors: Kiersten Ruisard, Sasha Aleksandrov, Sasha Zhukov, and Sarah Cousineau.</dd>

<dt>FEB 2023</dt>
<dd>Talk: [SNS accelerator synergies for muon collider R&D](https://agenda.hep.wisc.edu/event/2140/contributions/30224/attachments/9569/11827/2024-02-23_sns_synergies.pdf) at the Princeton Muon Collider Organizational Workshop at Princeton University.</dd>

<dt>DEC 2022</dt>
<dd> Contributed to article [Six-dimensional distributions at the SNS Beam Test Facility](https://higherlogicdownload.s3.amazonaws.com/APS/9cf62627-7088-4bd3-bf97-6adfc913f623/UploadedImages/APS_DPB_Newsletter_2022-2-2.pdf) in the annual APS DBP newsletter. Coauthors: Kiersten Ruisard, Sasha Aleksandrov.</dd>

<dt>OCT 2022</dt>
<dd>Talk: [Self-consistent, angular-momentum-dominated hadron beams for space charge mitigation](https://conference.sns.gov/event/335/contributions/528/attachments/892/8194/2022-10-26_Hoover_space_charge_workshop.pdf) at 5th ICFA Mini-Workshop on Space Charge in Knoxville.</dd>

<dt>AUG 2022</dt>
<dd>Talk: [Measurements of the five-dimensional phase space distribution of an intense ion beam](https://proceedings.jacow.org/napac2022/talks/frxd3_talk.pdf) at NAPAC22 in Albuquerque.</dd>

<dt>JUL 2022</dt>
<dd>Paper: [Four-dimensional emittance measurement at the Spallation Neutron Source](https://arxiv.org/pdf/2204.08303) accepted for publication in NIM:A.</dd>

<dt>APR 2022</dt>
<dd>Started postdoc at Oak Ridge National Laboratory, working on the Beam Test Facility (BTF) project at the SNS.</dd>

<dt>APR 2022</dt>
<dd>Lecture: [Accelerator research and development at the Spallation Neutron Source](https://www.dropbox.com/scl/fi/vnbsr8hp69mqsu9hwgjcy/2022-04-07_utk_sns_research.pdf?rlkey=gild5nf32ml15kc0qwjx0xsu2&st=zzpno4tf&dl=0) for the course "Particle Accelerators: Technology and Applications" in the Nuclear Engineering department at UTK.</dd>

<dt>APR 2022</dt>
<dd>Completed [Ph.D.](https://trace.tennessee.edu/utk_graddiss/7228) at the University of Tennessee, Knoxville.</dd>

<dt>OCT 2021</dt>
<dd>Talk: [Development of an injection-painted self-consistent beam at the Spallation Neutron Source](https://proceedings.jacow.org/hb2021/papers/moac3.pdf) at HB21 (presented remotely).</dd>

<dt>MAR 2021</dt>
<dd>Paper: [Computation of the matched envelope of the Danilov distribution](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.24.044201) accepted for publication in PRAB.</dd>

<dt>APR 2021</dt>
<dd>Talk: [Computation of the matched envelope of the Danilov distribution](https://www.dropbox.com/scl/fi/9829dxlatyj53vjqt6ryn/2021-04-20_aps_match.key?rlkey=9w8ib7brvxfbzpagt0u22tvp8&st=nf6ity2l&dl=0) at APS April Meeting (presented remotely).</dd>

<dt>AUG 2018</dt>
<dd>Started Ph.D. at the University of Tennessee, Knoxville.</dd>

<dt>AUG 2018</dt>
<dd>Graduated from Wheaton College (IL).</dd>

<dt>AUG 2014</dt>
<dd>Started B.S. degree Wheaton College (IL).</dd>

<dt>DEC 1997</dt>
<dd>Moved to Ypsilanti, Michigan, just outside Ann Arbor.</dd>

<dt>DEC 1995</dt>
<dd>Born in Hong Kong.</dd>

</dl>
