---
title: "Austin Hoover"
format:
  html:
    toc: true
    css: cv.css
    lightbox: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="../_extensions/quarto-ext/fontawesome/assets/css/all.min.css">
  pdf:
    pdf-engine: xelatex
    documentclass: article
    papersize: letter
    fontsize: 10pt
    geometry:
      - margin=0.8in
    toc: false
    colorlinks: true
    filters:
      - pdf.lua
    include-in-header: pdf-preamble.tex
---

::: {.cv-header}
::: {.cv-contact}
[<i class="fa-solid fa-envelope" aria-hidden="true"></i> hooveram@ornl.gov](mailto:hooveram@ornl.gov)
[·]{.contact-separator}
[<i class="fa-solid fa-link" aria-hidden="true"></i> austin-hoover.github.io](https://austin-hoover.github.io)
:::
:::

## Education and Employment

::: {.cv-entry}
Accelerator Physicist, Oak Ridge National Laboratory

::: {.cv-year}
2024–
:::
:::

::: {.cv-entry}
Postdoctoral Research Associate, Oak Ridge National Laboratory

::: {.cv-year}
2022–2024
:::
:::

::: {.cv-entry}
Ph.D. in Physics, University of Tennessee

::: {.cv-year}
2018–2022
:::
:::

::: {.cv-entry}
B.S. in Physics, Wheaton College (IL)

::: {.cv-year}
2014–2018
:::
:::

## Journal Articles

::: {.cv-entry}
*Demonstration of a novel phase space painting method in a coupled lattice to mitigate space charge in high-intensity hadron beams*. N. Evans, A. Hoover, T. Gorlov, and V. Morozov. Phys. Rev. Letters 136, 075002. [[link](https://doi.org/10.1103/bvwq-34jf)] [[arxiv](https://arxiv.org/pdf/2601.13517)] [[data](https://doi.org/10.5281/zenodo.15349989)]

::: {.cv-year}
2026
:::
:::

::: {.cv-entry}
*N-dimensional maximum-entropy tomography via particle sampling*. A. Hoover. Phys. Rev. Accel. Beams 28, L084601 (Letter, Editor's Choice). [[link](https://journals.aps.org/prab/pdf/10.1103/zl2h-3v32)] [[arxiv](https://arxiv.org/pdf/2409.17915)] [[code](https://doi.org/10.5281/zenodo.15271632)]

::: {.cv-year}
2025
:::
:::

::: {.cv-entry}
*Four-dimensional phase space tomography from one-dimensional measurements of a hadron beam*. A. Hoover. Phys. Rev. Accel. Beams 27, 122802. [[link](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.27.122802)] [[arxiv](https://arxiv.org/pdf/2409.02862)] [[data](https://doi.org/10.5281/zenodo.14009840)]

::: {.cv-year}
2024
:::
:::

::: {.cv-entry}
*High-dimensional maximum-entropy phase space tomography using normalizing flows*. A. Hoover and J.C. Wong. Phys. Rev. Research 6.3, 033163. [[link](https://journals.aps.org/prresearch/pdf/10.1103/PhysRevResearch.6.033163)] [[arxiv](https://arxiv.org/pdf/2406.00236)] [[code](https://github.com/austin-hoover/ment-flow)]

::: {.cv-year}
2024
:::
:::

::: {.cv-entry}
*Analysis of a hadron beam in five-dimensional phase space*. A. Hoover, K. Ruisard, A. Aleksandrov, A. Zhukov, and S. Cousineau. Phys. Rev. Accel. Beams 26.6, 064202. [[link](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.26.064202)] [[arxiv](https://arxiv.org/pdf/2301.04178)] [[data](https://doi.org/10.5281/zenodo.7517346)]

::: {.cv-year}
2023
:::
:::

::: {.cv-entry}
*Four-dimensional emittance measurement at the Spallation Neutron Source*. A. Hoover and N. Evans. Nucl. Instrum. Methods Phys. Res., Sect. A 1041, 167376. [[link](https://www.sciencedirect.com/science/article/abs/pii/S0168900222006805)] [[arxiv](https://arxiv.org/pdf/2204.08303)]

::: {.cv-year}
2022
:::
:::

::: {.cv-entry}
*Computation of the matched envelope of the Danilov distribution*. A. Hoover, N. Evans, and J. Holmes. Phys. Rev. Accel. Beams 24.4, 044201. [[link](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.24.044201)]

::: {.cv-year}
2022
:::
:::

## Conference/Workshop Proceedings

### Invited Talks

::: {.cv-entry}
*Eigenpainting for mitigation of space charge in high-intensity hadron beams*. International Particle Accelerator Conference.

::: {.cv-year}
2027
:::
:::

::: {.cv-entry}
*High-dimensional maximum-entropy phase space tomography*. North American Particle Accelerator Conference. [[paper](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/TUZN01.pdf)] [[slides](https://proceedings.jacow.org/napac2025/pdf/TUZN01_talk.pdf)]

::: {.cv-year}
2025
:::
:::

### Contributed Talks

::: {.cv-entry}
*Designing experiments to study large space charge tune shifts in the SNS accumulator ring*. ICFA Mini-Workshop on Space Charge. [[slides](https://indico.global/event/15713/contributions/162546/)]

::: {.cv-year}
2026
:::
:::

::: {.cv-entry}
*Four-dimensional phase space tomography from one-dimensional measurements of a hadron beam*. International Linear Accelerator Conference. [[slides](https://indico.jacow.org/event/117/contributions/15382/attachments/2514/8986/MO1P001-Austin_Hoover.pdf)] [[code](https://doi.org/10.5281/zenodo.21940430)]

::: {.cv-year}
2026
:::
:::

::: {.cv-entry}
*Bunch compression experiments at SNS*. International Muon Collider Collaboration Annual Meeting. [[slides](https://indico.cern.ch/event/1615465/contributions/7137183/)]

::: {.cv-year}
2026
:::
:::

::: {.cv-entry}
*Repurposing existing accelerator facilities for Muon Collider R&D*. APS Global Physics Summit. [[slides](../files/2026-03-17_aps.pdf)]

::: {.cv-year}
2026
:::
:::

::: {.cv-entry}
*Proton Driver for the Demonstrator and Muon Collider*. US Muon Collider Annual Meeting. [[slides](https://indico.uchicago.edu/event/479/contributions/1999/attachments/782/1296/main.pdf)]

::: {.cv-year}
2025
:::
:::

::: {.cv-entry}
*Bunch rotation experiments and benchmarking at SNS*. International Muon Collider Collaboration Meeting. [[slides](https://indico.desy.de/event/45968/contributions/186224/attachments/97097/133487/main.pptx)]

::: {.cv-year}
2025
:::
:::

::: {.cv-entry}
*SNS accelerator synergies for muon collider R&D*. Princeton Muon Collider Organizational Workshop. [[slides](https://agenda.hep.wisc.edu/event/2140/contributions/30224/attachments/9569/11827/2024-02-23_sns_synergies.pdf)]

::: {.cv-year}
2024
:::
:::

::: {.cv-entry}
*The impact of high-dimensional phase space correlations on the beam dynamics in a linear accelerator*. ICFA Workshop on High-Intensity and High-Brightness Hadron Beams. [[paper](https://accelconf.web.cern.ch/hb2023/papers/tuc1c2.pdf)] [[slides](https://accelconf.web.cern.ch/hb2023/talks/tuc1c2_talk.pdf)]

::: {.cv-year}
2023
:::
:::

::: {.cv-entry}
*Measurements of the five-dimensional phase space distribution of an intense ion beam*. North American Particle Accelerator Conference. [[paper](https://accelconf.web.cern.ch/napac2022/papers/frxd3.pdf)] [[slides](https://proceedings.jacow.org/napac2022/talks/frxd3_talk.pdf)]

::: {.cv-year}
2022
:::
:::

::: {.cv-entry}
*Accelerator research and development at the Spallation Neutron Source*. Particle Accelerators: Technology and Applications (UTK graduate course). [[slides](https://www.dropbox.com/scl/fi/vnbsr8hp69mqsu9hwgjcy/2022-04-07_utk_sns_research.pdf?rlkey=gild5nf32ml15kc0qwjx0xsu2&st=zzpno4tf&dl=0)]

::: {.cv-year}
2022
:::
:::

::: {.cv-entry}
*Self-consistent, angular-momentum-dominated hadron beams for space charge mitigation*. ICFA Mini-Workshop on Space Charge. [[slides](https://conference.sns.gov/event/335/contributions/528/attachments/892/8194/2022-10-26_Hoover_space_charge_workshop.pdf)]

::: {.cv-year}
2022
:::
:::

::: {.cv-entry}
*Development of an injection-painted self-consistent beam at the Spallation Neutron Source*. ICFA Workshop on High-Intensity and High-Brightness Hadron Beams. [[paper](https://proceedings.jacow.org/hb2021/papers/moac3.pdf)]

::: {.cv-year}
2021
:::
:::

::: {.cv-entry}
*Computation of the matched envelope of the Danilov distribution*. APS April Meeting. [[slides](https://www.dropbox.com/scl/fi/9829dxlatyj53vjqt6ryn/2021-04-20_aps_match.key?rlkey=9w8ib7brvxfbzpagt0u22tvp8&st=nf6ity2l&dl=0)]

::: {.cv-year}
2021
:::
:::

### Posters

::: {.cv-entry}
*Search for Vlasov-Poisson equilibrium distributions using generative models*. A. Hoover. International Particle Accelerator Conference. [[paper](https://ipac26.org/prepress/pdf/THP5350.pdf)]

::: {.cv-year}
2026
:::
:::

::: {.cv-entry}
*Feasibility of proton bunch compression in an operational high-power accelerator*. A. Hoover, V. Morozov, C. Piller, A. Narayan. North American Particle Accelerator Conference. [[paper](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/THP033.pdf)]

::: {.cv-year}
2025
:::
:::

::: {.cv-entry}
*MENT-Flow: maximum-entropy tomography using normalizing flows*. A. Hoover, C. Wong. International Particle Accelerator Conference. [[paper](https://www.jacow.org/ipac2024/pdf/WEPG65.pdf)]

::: {.cv-year}
2024
:::
:::

::: {.cv-entry}
*Detailed characterization of a five-dimensional phase space distribution*. A. Hoover, K. Ruisard, A. Aleksandrov, S. Cousineau, A. Zhukov. International Particle Accelerator Conference. [[paper](https://accelconf.web.cern.ch/ipac2023/pdf/WEPA028.pdf)]

::: {.cv-year}
2023
:::
:::

::: {.cv-entry}
*Simulation of 4D emittance measurement at the Spallation Neutron Source*. A. Hoover, N. Evans. International Particle Accelerator Conference. [[paper](https://proceedings.jacow.org/ipac2021/papers/thpab180.pdf)]

::: {.cv-year}
2021
:::
:::

### Coauthor

::: {.cv-entry}
*Beam loss modeling and mitigation due to intra-beam stripping*. S. Kakkar, V. Morozov, L. Lee, N. Evans, A. Zhukov, A. Hoover. North American Particle Accelerator Conference. [[paper](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/THP014.pdf)]

::: {.cv-year}
2025
:::
:::

::: {.cv-entry}
*Exploring space charge mitigation with eigenpainting at the SNS*. N.J. Evans, A. Hoover, T. Gorlov, V. Morozov. North American Particle Accelerator Conference. [[paper](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/TUP041.pdf)]

::: {.cv-year}
2025
:::
:::

::: {.cv-entry}
*Progress toward halo modeling at the SNS Beam Test Facility*. K. Ruisard, A. Aleksandrov, A. Hoover, T. Thompson, A. Zhukov. Linear Accelerator Conference. [[paper](https://proceedings.jacow.org/linac2024/pdf/THAA005.pdf)]

::: {.cv-year}
2024
:::
:::

::: {.cv-entry}
*Proposed muon collider R&D at the SNS*. V. Morozov, A. Hoover, D. Stratakis, F. Pilat, N. Evans, S. Cousineau. International Particle Accelerator Conference. [[paper](https://www.jacow.org/ipac2024/pdf/WEPR39.pdf)]

::: {.cv-year}
2024
:::
:::

::: {.cv-entry}
*Measurement and modeling of beam transport in the FODO line of the Spallation Neutron Source Beam Test Facility*. T. Thompson, K. Ruisard, A. Hoover, A. Aleksandrov, A. Zhukov. International Particle Accelerator Conference. [[paper](https://accelconf.web.cern.ch/ipac2024/pdf/TUAN2.pdf)]

::: {.cv-year}
2024
:::
:::

::: {.cv-entry}
*Status of Spallation Neutron Source Beam Test Facility and progress of beam dynamics studies*. K. Ruisard, A. Aleksandrov, S. Cousineau, R. Dickson, B. Han, A. Hoover, A. Shishlo, T. Thompson, V. Tzoganis, R. Welton, A. Zhukov. International Particle Accelerator Conference. [[paper](https://www.jacow.org/ipac2024/pdf/THPC75.pdf)]

::: {.cv-year}
2024
:::
:::

::: {.cv-entry}
*Self-consistent injection painting for space charge mitigation*. N. Evans, A. Hoover, T. Gorlov, V. Morozov. ICFA Workshop on High-Intensity and High-Brightness Hadron Beams. [[paper](https://inspirehep.net/files/d31c7f076dcde3b2bade3c13963bd187)]

::: {.cv-year}
2023
:::
:::

::: {.cv-entry}
*Measurements at peak operational beam current in the SNS beam test facility*. K. Ruisard, A. Hoover, A. Aleksandrov, A. Zhukov, S. Cousineau. International Particle Accelerator Conference. [[paper](https://accelconf.web.cern.ch/ipac2023/pdf/WEPA027.pdf)]

::: {.cv-year}
2023
:::
:::

::: {.cv-entry}
*Phase space painting of a self-consistent Danilov distribution in the SNS Ring*. N. Evans, A. Hoover, T. Gorlov, V. Morozov. International Particle Accelerator Conference. [[paper](https://proceedings.jacow.org/ipac2023/pdf/TUPM115.pdf)]

::: {.cv-year}
2023
:::
:::

::: {.cv-entry}
*Model/measurement comparison of the transverse phase space distribution of an RFQ-generated bunch at the SNS BTF*. K. Ruisard, A. Aleksandrov, S. Cousineau, A. Hoover, A. Zhukov. North American Particle Accelerator Conference. [[paper](https://www.osti.gov/servlets/purl/1973325)]

::: {.cv-year}
2022
:::
:::

::: {.cv-entry}
*Observation of current-driven features of 2.5 MeV ion bunch with complete and efficient 5D measurements at the SNS Beam Test Facility*. K. Ruisard, A. Aleksandrov, S. Cousineau, A. Hoover, A. Zhukov. International Linear Accelerator Conference. [[paper](https://accelconf.web.cern.ch/linac2022/papers/tupoge20.pdf)]

::: {.cv-year}
2022
:::
:::

::: {.cv-entry}
*Open XAL Status Report 2022*. A. Zhukov, A. Hoover, A. Shishlo, J. F. Esteban Müller, E. Laface, Y. Levinsen, N. Milas. International Particle Accelerator Conference. [[paper](https://accelconf.web.cern.ch/ipac2022/papers/tupotk029.pdf)]

::: {.cv-year}
2021
:::
:::

## Miscellaneous

::: {.cv-entry}
*Six Dimensional Distributions at the SNS Beam Test Facility*. K. Ruisard, A. Aleksandrov, A. Hoover. APS Division of Physics of Beams Annual Newsletter. [[link](https://higherlogicdownload.s3.amazonaws.com/APS/9cf62627-7088-4bd3-bf97-6adfc913f623/UploadedImages/APS_DPB_Newsletter_2022-2-2.pdf)]

::: {.cv-year}
2022
:::
:::


::: {.cv-entry}
*Towards the production of a self-consistent phase space distribution*. A. Hoover. PhD Diss., University of Tennessee. [[link](https://trace.tennessee.edu/utk_graddiss/7228)]

::: {.cv-year}
2022
:::
:::


## Seminars

::: {.cv-entry}
*Accelerator and beam physics research at ORNL*. Adlai E. Stevenson High School Physics Club.

::: {.cv-year}
2026
:::
:::

::: {.cv-entry}
*Accelerator research and development at the Spallation Neutron Source*. University of Tennessee Nuclear Engineering Department, graduate course (Particle Accelerators: Technology and Applications).

::: {.cv-year}
2022
:::
:::

## Teaching Experience

::: {.cv-entry}
Instructor, United States Particle Accelerator School, *Beam Physics with Intense Space Charge*. [[website](https://people.frib.msu.edu/~lund/uspas/bpisc_2026/)]

::: {.cv-year}
2026
:::
:::

::: {.cv-entry}
Teaching Assistant, United States Particle Accelerator School, *Accelerator Fundamentals*.

::: {.cv-year}
2021
:::
:::

::: {.cv-entry}
Graduate Teaching Assistant, Department of Physics, University of Tennessee.

::: {.cv-year}
2018–2019
:::
:::

::: {.cv-entry}
Teaching Assistant, Department of Physics, Wheaton College.

::: {.cv-year}
2018–2019
:::
:::

## Service

::: {.cv-entry}
Program committee, United States Muon Collider Collaboration (USMCC) Annual Meeting

::: {.cv-year}
2026
:::
:::

::: {.cv-entry}
Organizing committee, International Muon Collider Collaboration (IMCC) Annual Meeting

::: {.cv-year}
2026
:::
:::

::: {.cv-entry}
United States Muon Collider Collaboration (USMCC) Leadership Strategy Group (Proton Driver)

::: {.cv-year}
2025–
:::
:::

Reviewer for Physical Review Letters (1), Physical Review Accelerators and Beams (2), and Nature Communications Physics (1).
