---
title: Princeton Muon Collider Workshop
date: 2024-03-24
author: Austin Hoover
categories:
  - particle accelerators
  - conferences
  - muon collider
draft: true
---

Progress in particle physics will eventualy require a new laboratory. There are several options The Future Circular Collider (FCC) would collide ~100 TeV protons in a 100 km ring, using the LHC as a booster; the International Linear Collider (ILC) or Compact Linear Collider (CLIC) would collide electrons with positrons at ~1 TeV in a ~50 km linac; and the Muon Collider (MuC) would collide muons and antimuons at ~10 TeV in a ~10 km ring. 

Current estimates for the FCC are around 75 years to launch and billions of Euros. The accelerator would be a straightforward extension of the LHC, but it could take 10-20 years to develop the necessary 16 T dipole magnet technology. 

I had an interesting conversation with an experimental particle physicist. In his opinion, particle physicists undersell their work. He drew comparison to condensed matter physics, where experiments reveal exciting and unpredicted phenomena despite agreeing completely with the underlying theory of quantum mechanics. He argued that similar findings are commonplace at the LHC — new processes that do not contradict the Standard Model (SM) but are, nonetheless, unexpected and exciting — and that many of these findings belong in, e.g., the journal Nature. 

