---
title: "Papers"
format:
  html:
    css: style.css
---


## Peer-Reviewed

<dl class="papers-dl">

<dt>2026</dt>
<dd>
[Demonstration of a novel phase space painting method in a coupled lattice to mitigate space charge in high-intensity hadron beams](https://doi.org/10.1103/bvwq-34jf). 
N. Evans, A. Hoover. T. Gorlov, and V. Morozov. 
*Phys. Rev. Letters (Forthcoming)*.
</dd>

<dt>2025</dt>
<dd>
[N-dimensional maximum-entropy tomography via particle sampling](https://journals.aps.org/prab/pdf/10.1103/zl2h-3v32). 
A. Hoover. 
*Phys. Rev. Accel. Beams 28, L084601*.
</dd>

<dt>2024</dt>
<dd>
[Four-dimensional phase space tomography from one-dimensional measurements of a hadron beam](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.27.122802). 
A. Hoover.
*Phys. Rev. Accel. Beams 27, 122802*.
</dd>


<dt>2024</dt>
<dd>
[High-dimensional maximum-entropy phase space tomography using normalizing flows](https://journals.aps.org/prresearch/pdf/10.1103/PhysRevResearch.6.033163).
A. Hoover, and J.C. Wong.
*Phys. Rev. Research 6.3, 033163*.
</dd>

<dt>2023</dt>
<dd>
[Analysis of a hadron beam in five-dimensional phase space](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.26.064202).
A. Hoover, K. Ruisard, A. Aleksandrov, A. Zhukov, and S. Cousineau.
*Phys. Rev. Accel. Beams 26.6, 064202*.
</dd>

<dt>2022</dt>
<dd>
[Four-dimensional emittance measurement at the Spallation Neutron Source](https://www.sciencedirect.com/science/article/abs/pii/S0168900222006805).
A. Hoover and N. Evans.
*Nucl. Instrum. Methods Phys. Res., Sect. A 1041, 167376*
</dd>

<dt>2021</dt>
<dd>
[Computation of the matched envelope of the Danilov distribution](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.24.044201).
A. Hoover, N. Evans, and J. Holmes.
*Phys. Rev. Accel. Beams 24.4, 044201*.
</dd>

</dl>




## Conference Papers^[The following papers are not peer-reviewed. At most accelerator conferences (such as IPAC) contributions are limited to three pages in length and are meant to complement posters or talks. (There is an option for [light peer review](https://www.ipac26.org/light-peer-review/) but I've never tried it.) Papers often report work in progress, before submission to a journal, or summarize previously published work.]


### Invited


<dl class="papers-dl">

<dt>2025</dt>
<dd>
[High-dimensional maximum-entropy phase space tomography](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/TUZN01.pdf).
A. Hoover. *North American Particle Accelerator Conference* (2025).
</dd>

</dl>


### Contributed (First Author)

<dl class="papers-dl">

<dt>2025</dt>
<dd>
[Feasibility of proton bunch compression in an operational high-power accelerator](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/THP033.pdf).
A. Hoover, V. Morozov, C. Piller, A. Narayan.
*North American Particle Accelerator Conference* (2025).
</dd>

<dt>2024</dt>
<dd>
[MENT-Flow: maximum-entropy tomography using normalizing flows](https://www.jacow.org/ipac2024/pdf/WEPG65.pdf).
A. Hoover and C. Wong.
*International Particle Accelerator Conference*.
</dd>

<dt>2023</dt>
<dd>
[The impact of high-dimensional phase space correlations on the beam dynamics in a linear accelerator](https://accelconf.web.cern.ch/hb2023/papers/tuc1c2.pdf).
A. Hoover, K. Ruisard, A. Aleksandrov, S. Cousineau, A. Zhukov, A. Shishlo.
*ICFA Workshop on High-Intensity and High-Brightness Hadron Beams*.
</dd>

<dt>2023</dt>
<dd>
[Detailed characterization of a five-dimensional phase space distribution](https://accelconf.web.cern.ch/ipac2023/pdf/WEPA028.pdf).
A. Hoover, K. Ruisard, A. Aleksandrov, S. Cousineau, A. Zhukov.
*International Particle Accelerator Conference*.
</dd>

<dt>2022</dt>
<dd>
[Measurements of the five-dimensional phase space distribution of an intense ion beam](https://accelconf.web.cern.ch/napac2022/papers/frxd3.pdf).
A. Hoover, K. Ruisard, A. Aleksandrov, S. Cousineau, and A. Zhukov.
*North American Particle Accelerator Conference*.
</dd>

<dt>2021</dt>
<dd>
[Development of an injection-painted self-consistent beam at the Spallation Neutron Source](https://proceedings.jacow.org/hb2021/papers/moac3.pdf).
A. Hoover, N. Evans, T. Gorlov, J. Holmes.
*ICFA Workshop on High-Intensity and High-Brightness Hadron Beams*.
</dd>

<dt>2021</dt>
<dd>
[Simulation of 4D emittance measurement at the Spallation Neutron Source](). 
A. Hoover, N. Evans.
*International Particle Accelerator Conference*.
</dd>

<dt>2021</dt>
<dd>
[Computation of the matched envelope of the Danilov distribution](). APS April Meeting.
</dd>

</dl>



### Contributed (Coauthor)


<dl class="papers-dl">

<dt>2025</dt>
<dd>
[Beam loss modeling and mitigation due to intra-beam stripping](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/THP014.pdf).
S. Kakkar, V. Morozov, L. Lee, N. Evans, A. Zhukov, A. Hoover.
*North American Particle Accelerator Conference*.
</dd>


<dt>2025</dt>
<dd>
[Exploring space charge mitigation with eigenpainting at the SNS](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/TUP041.pdf).
N.J. Evans, A. Hoover, T. Gorlov, V. Morozov.
*North American Particle Accelerator Conference*.
</dd>

<dt>2024</dt>
<dd>
[Benchmark of linac model and phase space measurements at the SNS Beam Test Facility]().
K. Ruisard, A. Aleksandrov, A. Hoover, T. Thompson, and A. Zhukov.
*International Computational Accelerator Physics Conference*.
</dd>

<dt>2024</dt>
<dd>
[Progress toward halo modeling at the SNS Beam Test Facility](https://meow.elettra.eu/71/pdf/THAA005.pdf).
K. Ruisard, A. Aleksandrov, A. Hoover, T. Thompson, and A. Zhukov.
*Linear Accelerator Conference*.
</dd>

<dt>2024</dt>
<dd>
[Proposed muon collider R&D at the SNS](https://www.jacow.org/ipac2024/pdf/WEPR39.pdf).
V. Morozov, A. Hoover, D. Stratakis, F. Pilat, N. Evans, and S. Cousineau.
*International Particle Accelerator Conference*.
</dd>

<dt>2024</dt>
<dd>
[Measurement and modeling of beam transport in the FODO line of the Spallation Neutron Source Beam Test Facility](https://accelconf.web.cern.ch/ipac2024/pdf/TUAN2.pdf).
T. Thompson, K. Ruisard, A. Hoover, A. Aleksandrov, and A. Zhukov.
*International Particle Accelerator Conference*.
</dd>

<dt>2024</dt>
<dd>
[Status of Spallation Neutron Source Beam Test Facility and progress of beam dynamics studies](https://www.jacow.org/ipac2024/pdf/THPC75.pdf).
K. Ruisard, A. Aleksandrov, S. Cousineau, R. Dickson, B. Han, A. Hoover, A. Shishlo, T. Thompson, V. Tzoganis, R. Welton, and A. Zhukov.
*International Particle Accelerator Conference*.
</dd>

<dt>2023</dt>
<dd>
[Self-consistent injection painting for space charge mitigation](https://inspirehep.net/files/d31c7f076dcde3b2bade3c13963bd187).
N. Evans, A. Hoover, T. Gorlov, V. Morozov.
*ICFA Workshop on High-Intensity and High-Brightness Hadron Beams*.
</dd>

<dt>2023</dt>
<dd>
[Measurements at peak operational beam current in the SNS beam test facility](https://accelconf.web.cern.ch/ipac2023/pdf/WEPA027.pdf).
K. Ruisard, A. Hoover, A. Aleksandrov, A. Zhukov, S. Cousineau.
*International Particle Accelerator Conference*.
</dd>

<dt>2023</dt>
<dd>
[Phase space painting of a self-consistent Danilov distribution in the SNS Ring]().
N. Evans, A. Hoover, T. Gorlov, V. Morozov.
*International Particle Accelerator Conference*.
</dd>

<dt>2022</dt>
<dd>
[Model/measurement comparison of the transverse phase space distribution of an RFQ-generated bunch at the SNS BTF]().
K. Ruisard, A. Aleksandrov, S. Cousineau, A. Hoover, A. Zhukov.
*North American Particle Accelerator Conference*.
</dd>

<dt>2022</dt>
<dd>
[Observation of current- driven features of 2.5 MeV ion bunch with complete and efficient 5D measurements at the SNS Beam Test Facility](https://accelconf.web.cern.ch/linac2022/papers/tupoge20.pdf).
K. Ruisard, A. Aleksandrov, S. Cousineau. A. Hoover, A. Zhukov.
*International Linear Accelerator Conference*
</dd>

<dt>2021</dt>
<dd>
[Open XAL Status Report 2022](https://accelconf.web.cern.ch/ipac2022/papers/tupotk029.pdf).
A. Zhukov, A. Hoover, A. Shishlo,  J. F. Esteban Müller, E. Laface, Y. Levinsen, N. Milas.
*International Particle Accelerator Conference*
</dd>

</dl>




## Miscellaneous

<dl class="papers-dl">

<dt>2022</dt>
<dd>
[Six-dimensional distributions at the SNS Beam Test Facility](https://higherlogicdownload.s3.amazonaws.com/APS/9cf62627-7088-4bd3-bf97-6adfc913f623/UploadedImages/APS_DPB_Newsletter_2022-2-2.pdf).
K. Ruisard, A. Aleksandrov, A. Hoover.
*APS Division of Physics of Beams Annual Newsletter* (page 38).
</dd>

<dt>2022</dt>
<dd>
[Towards the production of a self-consistent phase space distribution](https://trace.tennessee.edu/utk_graddiss/7228).
A. Hoover. *PhD Diss., University of Tennessee*.
</dd>

</dl>