---
title: "High-dimensional phase space density measurements"
date: 2023-05-28
author: Austin Hoover
categories: [accelerators, high-dimensional data, visualization]
bibliography: references.bib
csl: american-physics-society.csl
---


## Difficulties modeling intense hadron beam dynamics

Intense hadron beams have many uses---as drivers for neutron production, muon production, nuclear energy production, etc. These beams are generated by repeatedly accelerating small bunches of particles in a linac. A few accelerators have now reached a beam power of 1 MW, and several future accelerators aim to operate near 5 MW. 

The beam power in the linac is limited by beam loss: some particles hit the "walls" of the accelerator during their journey, causing radio-activation. Beam loss must be kept below 1 W/m averaged along the beamline. For a 1 MW beam, this corresponds to a fractional beam loss of $10^{-6}$ --- one out of every million particles. Current facilities are creeping toward this limit.

Unfortunately, beam loss is difficult to predict. Part of the difficulty is that there are significant uncertainties in the electromagnetic fields distributed along the linac (which is hundreds of meters long). Additionally, the beam's evolution is affected by its own electric field (space charge), causing a dependence on the initial distribution of particles in position-momentum space (phase space). The initial phase space distribution is largely unknown. These uncertainties make it difficult to predict even the root-mean-square (rms) beam size evolution, let alone low levels of beam loss.

This problem was addressed in an important experiments at the Low-Energy Test Accelerator (LEDA) at Los Alamos National Laboratory. One-dimensional (1D) profiles of the beam were measured after transport through a periodic array of quadrupole magnets, then compared to particle-in-cell (PIC) simulations with various initial beam distributions. The measured profiles exhibited a dense core surrounded by a low-density "halo" with large spatial extent. Although good agreement was found in the beam core, the halo regions did not agree. 

[Image]


## High-dimensional phase space measurements



## The SNS Beam Test Facility (BTF)


## High-dimensional data visualization
## Improving the accelerator model