---
title: "Presentations"
format:
  html:
    lightbox: false
    css: ../style/style.css
---

*Note: papers at conferences such as IPAC and NAPAC are limited to three pages in length and are meant to complement posters or talks. They are not peer reviewed and often report work in progress or summarize published work. (There is an option for [light peer review](https://www.ipac26.org/light-peer-review/) but I've never tried it.)*


## Talks

<dl class="papers-dl">

<dt>2025</dt>
<dd>
**High-dimensional maximum-entropy phase space tomography** \
*North American Particle Accelerator Conference* \
[[paper](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/TUZN01.pdf)]
[[slides](https://drive.google.com/file/d/1D6URvUgqFryMU3Eq70PdiAzkym7n7SkZ/view?usp=share_link)]
</dd>

<dt>2025</dt>
<dd>
**Proton Driver for the Demonstrator and Muon Collider** \
*US Muon Collider Annual Meeting* \
[[slides](https://indico.uchicago.edu/event/479/contributions/1999/attachments/782/1296/main.pdf)]
</dd>

<dt>2025</dt>
<dd>
**Bunch rotation experiments and benchmarking at SNS** \
*International Muon Collider Collaboration Meeting* \
[[slides](https://indico.desy.de/event/45968/contributions/186224/attachments/97097/133487/main.pptx)]
</dd>

<dt>2024</dt>
<dd>
**SNS accelerator synergies for muon collider R&D** \
*Princeton Muon Collider Organizational Workshop* \
[[slides](https://agenda.hep.wisc.edu/event/2140/contributions/30224/attachments/9569/11827/2024-02-23_sns_synergies.pdf)]
</dd>

<dt>2023</dt>
<dd>
**The impact of high-dimensional phase space correlations on the beam dynamics in a linear accelerator** \
*ICFA Workshop on High-Intensity and High-Brightness Hadron Beams* \
[[paper](https://accelconf.web.cern.ch/hb2023/papers/tuc1c2.pdf)]
[[slides](https://accelconf.web.cern.ch/hb2023/talks/tuc1c2_talk.pdf)]
</dd>

<dt>2022</dt>
<dd>
**Measurements of the five-dimensional phase space distribution of an intense ion beam** \
*North American Particle Accelerator Conference* \
[[paper](https://accelconf.web.cern.ch/napac2022/papers/frxd3.pdf)]
[[slides](https://proceedings.jacow.org/napac2022/talks/frxd3_talk.pdf)]
</dd>

<dt>2021</dt>
<dd>
**Development of an injection-painted self-consistent beam at the Spallation Neutron Source** \
*ICFA Workshop on High-Intensity and High-Brightness Hadron Beams* \
[[paper](https://proceedings.jacow.org/hb2021/papers/moac3.pdf)]
</dd>

<dt>2022</dt>
<dd>
**Accelerator research and development at the Spallation Neutron Source** \
*Particle Accelerators: Technology and Applications (UTK graduate course)* \
[[slides](https://www.dropbox.com/scl/fi/vnbsr8hp69mqsu9hwgjcy/2022-04-07_utk_sns_research.pdf?rlkey=gild5nf32ml15kc0qwjx0xsu2&st=zzpno4tf&dl=0)]
</dd>

<dt>2021</dt>
<dd>
**Computation of the matched envelope of the Danilov distribution** \
*APS April Meeting* \
[[slides](https://www.dropbox.com/scl/fi/9829dxlatyj53vjqt6ryn/2021-04-20_aps_match.key?rlkey=9w8ib7brvxfbzpagt0u22tvp8&st=nf6ity2l&dl=0)]
</dd>

<dt>2022</dt>
<dd>
**Self-consistent, angular-momentum-dominated hadron beams for space charge mitigation** \
*ICFA Mini-Workshop on Space Charge* \
[[slides](https://conference.sns.gov/event/335/contributions/528/attachments/892/8194/2022-10-26_Hoover_space_charge_workshop.pdf)]
</dd>

</dl>



## Posters

<dl class="papers-dl">

<dt>2025</dt>
<dd>
**Feasibility of proton bunch compression in an operational high-power accelerator** \
A. Hoover, V. Morozov, C. Piller, A. Narayan \
*North American Particle Accelerator Conference* \
[[paper](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/THP033.pdf)]
</dd>

<dt>2024</dt>
<dd>
**MENT-Flow: maximum-entropy tomography using normalizing flows** \
A. Hoover, C. Wong \
*International Particle Accelerator Conference* \
[[paper](https://www.jacow.org/ipac2024/pdf/WEPG65.pdf)]
</dd>

<dt>2023</dt>
<dd>
**Detailed characterization of a five-dimensional phase space distribution** \
A. Hoover, K. Ruisard, A. Aleksandrov, S. Cousineau, A. Zhukov \
*International Particle Accelerator Conference*.
[[paper](https://accelconf.web.cern.ch/ipac2023/pdf/WEPA028.pdf)]
</dd>

<dt>2021</dt>
<dd>
**Simulation of 4D emittance measurement at the Spallation Neutron Source** \
A. Hoover, N. Evans \
*International Particle Accelerator Conference* \
[[paper](https://proceedings.jacow.org/ipac2021/papers/thpab180.pdf)]
</dd>

</dl>



## Coauthor

<dl class="papers-dl">

<dt>2025</dt>
<dd>
**Beam loss modeling and mitigation due to intra-beam stripping** \
S. Kakkar, V. Morozov, L. Lee, N. Evans, A. Zhukov, A. Hoover \
*North American Particle Accelerator Conference* \
[[paper](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/THP014.pdf)]
</dd>


<dt>2025</dt>
<dd>
**Exploring space charge mitigation with eigenpainting at the SNS** \
N.J. Evans, A. Hoover, T. Gorlov, V. Morozov \
*North American Particle Accelerator Conference* \
[[paper](https://prebys.physics.ucdavis.edu/NAPAC-25/proceedings/pdf/TUP041.pdf)]
</dd>

<dt>2024</dt>
<dd>
**Progress toward halo modeling at the SNS Beam Test Facility** \
K. Ruisard, A. Aleksandrov, A. Hoover, T. Thompson, A. Zhukov \
*Linear Accelerator Conference* \
[[paper](https://proceedings.jacow.org/linac2024/pdf/THAA005.pdf)]
</dd>

<dt>2024</dt>
<dd>
**Proposed muon collider R&D at the SNS** \
V. Morozov, A. Hoover, D. Stratakis, F. Pilat, N. Evans, S. Cousineau \
*International Particle Accelerator Conference* \
[[paper](https://www.jacow.org/ipac2024/pdf/WEPR39.pdf)]
</dd>

<dt>2024</dt>
<dd>
**Measurement and modeling of beam transport in the FODO line of the Spallation Neutron Source Beam Test Facility** \
T. Thompson, K. Ruisard, A. Hoover, A. Aleksandrov, A. Zhukov \
*International Particle Accelerator Conference* \
[[paper](https://accelconf.web.cern.ch/ipac2024/pdf/TUAN2.pdf)]
</dd>

<dt>2024</dt>
<dd>
**Status of Spallation Neutron Source Beam Test Facility and progress of beam dynamics studies** \
K. Ruisard, A. Aleksandrov, S. Cousineau, R. Dickson, B. Han, A. Hoover, A. Shishlo, T. Thompson, V. Tzoganis, R. Welton, A. Zhukov \
*International Particle Accelerator Conference* \
[[paper](https://www.jacow.org/ipac2024/pdf/THPC75.pdf)]
</dd>

<dt>2023</dt>
<dd>
**Self-consistent injection painting for space charge mitigation** \
N. Evans, A. Hoover, T. Gorlov, V. Morozov \
*ICFA Workshop on High-Intensity and High-Brightness Hadron Beams* \
[[paper](https://inspirehep.net/files/d31c7f076dcde3b2bade3c13963bd187)]
</dd>

<dt>2023</dt>
<dd>
**Measurements at peak operational beam current in the SNS beam test facility** \
K. Ruisard, A. Hoover, A. Aleksandrov, A. Zhukov, S. Cousineau \
*International Particle Accelerator Conference* \
[[paper](https://accelconf.web.cern.ch/ipac2023/pdf/WEPA027.pdf)]
</dd>

<dt>2023</dt>
<dd>
**Phase space painting of a self-consistent Danilov distribution in the SNS Ring** \
N. Evans, A. Hoover, T. Gorlov, V. Morozov \
*International Particle Accelerator Conference* \
[[paper](https://proceedings.jacow.org/ipac2023/pdf/TUPM115.pdf)]
</dd>

<dt>2022</dt>
<dd>
**Model/measurement comparison of the transverse phase space distribution of an RFQ-generated bunch at the SNS BTF** \
K. Ruisard, A. Aleksandrov, S. Cousineau, A. Hoover, A. Zhukov \
*North American Particle Accelerator Conference* \
[[paper](https://www.osti.gov/servlets/purl/1973325)]
</dd>

<dt>2022</dt>
<dd>
**Observation of current- driven features of 2.5 MeV ion bunch with complete and efficient 5D measurements at the SNS Beam Test Facility** \
K. Ruisard, A. Aleksandrov, S. Cousineau. A. Hoover, A. Zhukov \
*International Linear Accelerator Conference* \
[[paper](https://accelconf.web.cern.ch/linac2022/papers/tupoge20.pdf)]
</dd>

<dt>2021</dt>
<dd>
**Open XAL Status Report 2022** \
A. Zhukov, A. Hoover, A. Shishlo,  J. F. Esteban Müller, E. Laface, Y. Levinsen, N. Milas \
*International Particle Accelerator Conference* \
[[paper](https://accelconf.web.cern.ch/ipac2022/papers/tupotk029.pdf)]
</dd>


</dl>
